site_name: Training sessions
site_description: Overview of training sessions on scientific computing
site_author: Geert Jan Bex
nav:
- Introduction: 'index.md'
- Learning paths:
  - Data science: 'learning_path_data_science.md'
  - HPC applciation development: 'learning_path_hpc_application_development.md'
  - Using HPC applications: 'learning_path_using_hpc_applications.md'
- Subjects:
  - Computational skills: 'computational_skills.md'
  - Using HPC systems: 'using_hpc_systems.md'
  - Programming: 'programming.md'
  - Software engineering: 'software_engineering.md'
  - C++: 'cpp.md'
  - C: 'c.md'
  - Fortran: 'fortran.md'
  - Python: 'python.md'
  - Parallel computing: 'parallel_computing.md'
  - GPU computing: 'gpu_computing.md'
  - Data analysis and visualization: 'data_analysis_and_visualization.md'
  - AI and machine learning: 'ai_and_machine_learning.md'
- Info:
  - Contact: 'contact.md'
  - Code of conduct: 'code_of_conduct.md'
  - License: 'license.md'
  # site_dir: html_docs/training_sessions
theme: readthedocs
plugins:
  - search
  - mermaid2
